_parent_: projects/neuralangelo/configs/custom/iterative_exps_no_prev_init.yaml
data:
    root: datasets/actor5_seq2_176_274/
    num_frames: 99
model:
    object:
        canonical_dir: logs/dynamic_reconstruction/actor5_seq2_176_274_canonical/epoch_08333_iteration_000250000_checkpoint.pt
