_parent_: projects/neuralangelo/configs/neus2_less_iter.yaml
data:
    type: projects.neuralangelo.multicam_data
    canonical: false
    target_frame: 2
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: datasets/actor4_287_310/
    train:
        image_size:
        - 1022
        - 747
    val:
        image_size:
        - 511
        - 373
model:
    appear_embed:
        enabled: false
    object:
        canonical_dir: logs/dynamic_reconstruction/actor4_template_large_movement/canonical.pt
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 16
            mlp:
                inside_out: false
        deform:
            num_frames: 24
            encoding:
                type: hashgrid  
                levels: 16
                hashgrid:
                    min_logres: 5
                    max_logres: 11
                    dict_size: 20
                    dim: 4
                    range: [-2,2]
                coarse2fine:
                    enabled: True
                    init_active_level: 4
                    step: 5000
