_parent_: projects/neuralangelo/configs/custom/iterative_exps_bg.yaml
data:
    root: ../../neuralangelo4d/datasets/actor6_seq2_180_286/
    num_frames: 30
model:
    object:
        canonical_dir: logs/dynamic_reconstruction/actor6_seq2_180_286_canonical_replicate/epoch_08333_iteration_000250000_checkpoint.pt
