_parent_: projects/neuralangelo/configs/custom/iterative_exps_deform_only.yaml
data:
    root: datasets/actor6_seq2_62_162/
    num_frames: 101
model:
    object:
        canonical_dir: logs/dynamic_reconstruction/actor6_seq2_62_162_canonical/epoch_08333_iteration_000250000_checkpoint.pt
