_parent_: projects/neuralangelo/configs/custom/iterative_exps_deform_only.yaml
data:
    root: datasets/actor1_140_204/
    num_frames: 65
model:
    object:
        canonical_dir: logs/dynamic_reconstruction/actor1_140_204_canonical/epoch_08333_iteration_000250000_checkpoint.pt
