_parent_: projects/neuralangelo/configs/neus2_less_iter.yaml
data:
    type: projects.neuralangelo.multicam_data
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: datasets/actor4_5frames/
    train:
        image_size:
        - 1022
        - 747
    val:
        image_size:
        - 511
        - 373
model:
    appear_embed:
        enabled: false
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 4
            mlp:
                inside_out: false
        deform:
            num_frames: 4
            encoding:
                type: hypergrid
                levels: 16
                hashgrid:
                    min_logres: 5
                    max_logres: 11
                    dict_size: 20
                    dim: 4
                    range: [-2,2]
                coarse2fine:
                    enabled: True
                    init_active_level: 2
                    step: 5000
