_parent_: projects/neuralangelo/configs/custom/iterative_exps_no_prev_init.yaml
data:
    root: datasets/actor4_73_170/
    num_frames: 98
model:
    object:
        canonical_dir: logs/dynamic_reconstruction/actor4_73_170_canonical/epoch_08333_iteration_000250000_checkpoint.pt
