max_iter: 5000
_parent_: projects/neuralangelo/configs/neus2_less_iter.yaml
data:
    type: projects.neuralangelo.multicam_data
    canonical: false
    target_frame: 2
    num_frames: 24
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: datasets/actor4_287_310/
    train:
        image_size:
        - 1022
        - 747
    val:
        image_size:
        - 511
        - 373
model:
    background:
        enabled: False
        white: False
    appear_embed:
        enabled: false
    object:
        canonical_dir: logs/dynamic_reconstruction/actor4_template_nobgr/epoch_08333_iteration_000250000_checkpoint.pt
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 16
            mlp:
                inside_out: false
            gradient:
                mode: analytical
        deform:
            encoding:
                type: fourier  
                levels: 4
                coarse2fine:
                    enabled: True
                    init_active_level: 1
                    step: 1000
            mlp:
                num_layers: 6
                hidden_dim: 128
                skip: [3]
                activ: relu
                activ_params: {}
                weight_norm: True

optim:
    sched:
        iteration_mode: True
        type: two_steps_with_warmup
        warm_up_end: 40
        two_steps: [25000,40000]
        gamma: 10.0

trainer:
    loss_weight:
        mask: 0.1
