_parent_: projects/neuralangelo/configs/base.yaml
data:
    type: projects.neuralangelo.multicam_data
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: datasets/vci_capture_mohammed/
    train:
        image_size:
        - 914
        - 1057
    val:
        image_size:
        - 300
        - 346
model:
    appear_embed:
        enabled: false
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 8
            mlp:
                inside_out: false
